municipio: "Londrina"
uf: "PR"
ibge_cod_municipio: "4113700"
arcgis_zoneamento_layer: "https://geo.londrina.pr.gov.br/server/rest/services/abertos_zoneamento/Uso_e_Ocupa%C3%A7%C3%A3o_do_Solo_VIGENTE/MapServer/0"
